name: testing - Deploy to S3

on:
    push:
        branches:
            - main
            - develop

           

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with: 
                node-version: '22'
                cache: npm

            - name: CHECK PATH
              run: pwd

            - name: Install dependencies
              run: npm ci

            - name: Build angular
              run: npm run build

            - name: Debug - Ver estructura de carpetas
              run: ls -R dist

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                aws-region: us-east-1

            - name: Deploy to S3
              run: aws s3 sync dist/testing s3://amzn-front --delete --exclude ".*"