name: testing - Deploy to S3

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recomiendo usar LTS (20) en lugar de 22 por estabilidad, pero 22 funciona.
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build angular
        run: npm run build

      - name: Debug - Verificar ruta real
        run: ls -R dist
        # Este paso es vital. Mira los logs después de correrlo para ver si existe 
        # dist/testing o dist/testing/browser

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Solo necesario si usas credenciales temporales (ej. AWS Academy)
          aws-region: us-east-1

      # CORRECCIÓN DE CACHÉ: 
      # Paso 1: Subir assets (imágenes, js, css) con caché largo (1 año)
      # Nota: Ajusta la ruta 'dist/testing' si tu build genera 'dist/testing/browser'
      - name: Deploy Assets to S3 (Cache Forever)
        run: |
          aws s3 sync dist/testing s3://amzn-front \
          --delete \
          --exclude ".*" \
          --exclude "index.html" \
          --cache-control "max-age=31536000,public"

      # Paso 2: Subir index.html SIN caché para que los usuarios siempre vean los cambios
      - name: Deploy Index to S3 (No Cache)
        run: |
          aws s3 cp dist/testing/index.html s3://amzn-front/index.html \
          --cache-control "no-cache, no-store, must-revalidate"